### PR TITLE
volatile and pragma off

### PR DESCRIPTION
**Pull request by ghost**
Good point? :)

### CODE REVIEW

**Comment by ghost** [comment]
Example output: https://pastebin.com/vEgF9g4m

**Comment by ghost** [comment]
__forceinline maybe don't needed use

**Comment by gehaxelt** [comment]
Hi,
why did you close this one?

**Comment by ghost** [comment]
thought the project was dead @gehaxelt

**Comment by gehaxelt** [comment]
No it's not. 

Can I reopen and merge it?

**Comment by ghost** [comment]
Yes
Do it

And remove __forceinline it is useless

**Pull request merged**
